Repository LamaraBenz/RestAPI_Automation_Framework_Team4, pull requests merged in 2020-06, with the labels that each got.

#4 1st commit to be merged
  Generic/src/main/java/TemporaryClass.java
Labels: documentation

#2 first commit
  Generic/src/main/java/TemporaryClass.java
Labels: enhancement

#6 usma
  Generic/src/main/java/TemporaryClass.java
Labels: bug

#5 30215 ny karim
  Generic/src/main/java/TemporaryClass.java
Labels: documentation
